//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        public int id { get; set; }
        public string username { get; set; }
        public string passwordhash { get; set; }
        public string saltvalue { get; set; }
        public System.DateTime ngaytao { get; set; }
        public bool dangsudung { get; set; }
    }
}
